/**
 * Granular permission keys and default role bundles.
 * Single source of truth shared by the DB seed, server-side authorization,
 * and tests. See docs/PERMISSIONS_MATRIX.md.
 *
 * Authorization is permission-based, never role-name based (CLAUDE.md §2).
 */

export const PERMISSION_KEYS = [
  // Platform (super admin)
  'platform.tenants.create',
  'platform.tenants.suspend',
  'platform.plans.manage',
  'platform.health.read',
  'platform.integrations.manage',
  'platform.models.configure',
  'platform.domains.manage',
  'platform.billing.read',
  'platform.impersonate',
  // Tenant settings
  'settings.branding.manage',
  'settings.org.manage',
  'settings.roles.manage',
  'settings.integrations.manage',
  'settings.security.manage',
  'settings.retention.manage',
  'settings.audit.read',
  // Users & team
  'users.invite',
  'users.manage',
  'agents.manage',
  'agents.availability.manage',
  'team.performance.read',
  // Projects & inventory
  'projects.read',
  'projects.manage',
  'inventory.read',
  'inventory.manage',
  'inventory.import',
  'knowledge.manage',
  'knowledge.approve',
  'staledata.resolve',
  // Leads
  'leads.read.assigned',
  'leads.read.team',
  'leads.read.all',
  'leads.create',
  'leads.update',
  'leads.assign',
  'leads.reassign',
  'leads.merge',
  'leads.export',
  'leads.classify.override',
  // Conversations
  'conversations.read.assigned',
  'conversations.read.private',
  'conversations.read.all',
  'conversations.read.team',
  'conversations.read.metadata',
  'conversations.reply',
  'conversations.takeover',
  'conversations.transfer',
  'conversations.assign',
  'conversations.close',
  'conversations.reopen',
  'conversations.priority.manage',
  'conversations.tags.manage',
  'conversations.notes.create',
  'conversations.notes.manage',
  'conversations.ai.resume',
  'conversations.export',
  'messages.redact',
  'canned_replies.manage',
  'website_chat.manage',
  'website_chat.view_sessions',
  'consent.manage',
  'dnc.manage',
  // Knowledge & AI (Phase 5A)
  'knowledge.read',
  'knowledge.create',
  'knowledge.edit',
  'knowledge.review',
  'knowledge.archive',
  'knowledge.conflicts.resolve',
  'ai.settings.read',
  'ai.settings.manage',
  'ai.providers.manage',
  'ai.prompts.manage',
  'ai.test_lab.use',
  'ai.runs.read',
  'ai.feedback.create',
  'ai.copilot.use',
  'ai.shadow.manage',
  'ai.usage.read',
  // Phase 5B.0 responder runtime + activation (record-only; no live send)
  'responder.activation.request',
  'responder.activation.approve',
  'responder.channel.manage',
  'responder.killswitch.manage',
  // Phase 6A lead scoring
  'scoring.read',
  'scoring.run',
  'scoring.override',
  'scoring.models.read',
  'scoring.models.manage',
  'scoring.models.approve',
  'scoring.signals.manage',
  'scoring.evaluation.use',
  // Phase 6B project matching
  'matching.read',
  'matching.run',
  'matching.override',
  'matching.feedback.create',
  'matching.models.read',
  'matching.models.manage',
  'matching.models.approve',
  'matching.evaluation.use',
  // Phase 7A external integrations & channels
  'integrations.read',
  'integrations.manage',
  'integrations.credentials.manage',
  'integrations.events.read',
  'integrations.events.replay',
  'integrations.health.read',
  'integrations.mappings.manage',
  'channels.whatsapp.read',
  'channels.whatsapp.manage',
  'channels.whatsapp.templates.manage',
  'channels.whatsapp.test',
  'channels.email.read',
  'channels.email.manage',
  'channels.email.rules.manage',
  'channels.email.test',
  'channels.human_send.simulate',
  // Pipeline & sales ops
  'pipeline.configure',
  'pipeline.move',
  'tasks.manage',
  'calls.manage',
  'sitevisits.read',
  'sitevisits.manage',
  // Scoring & automation
  'scoring.read',
  'scoring.edit',
  'scoring.approve',
  'scoring.publish',
  'automations.manage',
  'assignment.configure',
  // Marketing
  'campaigns.manage',
  'sources.manage',
  'forms.manage',
  'attribution.read',
  'analytics.marketing.read',
  // Analytics
  'analytics.sales.read',
  'analytics.agents.read',
  'analytics.ai.read',
  'analytics.cost.read',
  // Billing
  'billing.read',
  'billing.manage',
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const PERMISSION_SET: ReadonlySet<PermissionKey> = new Set(PERMISSION_KEYS);

export function isPermissionKey(value: string): value is PermissionKey {
  return PERMISSION_SET.has(value as PermissionKey);
}

/** Default tenant role slugs. Tenants may clone and customize these. */
export const DEFAULT_ROLE_SLUGS = [
  'super_admin',
  'client_admin',
  'marketing_manager',
  'sales_manager',
  'sales_agent',
  'project_maintenance',
  'viewer',
] as const;

export type DefaultRoleSlug = (typeof DEFAULT_ROLE_SLUGS)[number];

/**
 * Default permission bundles per role (docs/PERMISSIONS_MATRIX.md §2).
 * `super_admin` holds platform-scope permissions only — no silent tenant-data
 * access (tenant access requires the audited impersonation flow).
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<DefaultRoleSlug, PermissionKey[]> = {
  super_admin: [
    'platform.tenants.create',
    'platform.tenants.suspend',
    'platform.plans.manage',
    'platform.health.read',
    'platform.integrations.manage',
    'platform.models.configure',
    'platform.domains.manage',
    'platform.billing.read',
    'platform.impersonate',
  ],
  client_admin: [
    'settings.branding.manage',
    'settings.org.manage',
    'settings.roles.manage',
    'settings.integrations.manage',
    'settings.security.manage',
    'settings.retention.manage',
    'settings.audit.read',
    'users.invite',
    'users.manage',
    'agents.manage',
    'agents.availability.manage',
    'team.performance.read',
    'projects.read',
    'projects.manage',
    'inventory.read',
    'inventory.manage',
    'inventory.import',
    'knowledge.manage',
    'knowledge.approve',
    'knowledge.read',
    'knowledge.create',
    'knowledge.edit',
    'knowledge.review',
    'knowledge.archive',
    'knowledge.conflicts.resolve',
    'ai.settings.read',
    'ai.settings.manage',
    'ai.providers.manage',
    'ai.prompts.manage',
    'ai.test_lab.use',
    'ai.runs.read',
    'ai.feedback.create',
    'ai.copilot.use',
    'ai.shadow.manage',
    'ai.usage.read',
    'responder.activation.request',
    'responder.activation.approve',
    'responder.channel.manage',
    'responder.killswitch.manage',
    'scoring.read',
    'scoring.run',
    'scoring.override',
    'scoring.models.read',
    'scoring.models.manage',
    'scoring.models.approve',
    'scoring.signals.manage',
    'scoring.evaluation.use',
    'matching.read',
    'matching.run',
    'matching.override',
    'matching.feedback.create',
    'matching.models.read',
    'matching.models.manage',
    'matching.models.approve',
    'matching.evaluation.use',
    'integrations.read',
    'integrations.manage',
    'integrations.credentials.manage',
    'integrations.events.read',
    'integrations.events.replay',
    'integrations.health.read',
    'integrations.mappings.manage',
    'channels.whatsapp.read',
    'channels.whatsapp.manage',
    'channels.whatsapp.templates.manage',
    'channels.whatsapp.test',
    'channels.email.read',
    'channels.email.manage',
    'channels.email.rules.manage',
    'channels.email.test',
    'channels.human_send.simulate',
    'staledata.resolve',
    'leads.read.all',
    'leads.create',
    'leads.update',
    'leads.assign',
    'leads.reassign',
    'leads.merge',
    'leads.export',
    'leads.classify.override',
    'conversations.read.private',
    'conversations.reply',
    'conversations.takeover',
    'conversations.transfer',
    'pipeline.configure',
    'pipeline.move',
    'tasks.manage',
    'calls.manage',
    'sitevisits.read',
    'sitevisits.manage',
    'scoring.read',
    'scoring.edit',
    'scoring.approve',
    'scoring.publish',
    'automations.manage',
    'assignment.configure',
    'campaigns.manage',
    'sources.manage',
    'forms.manage',
    'attribution.read',
    'analytics.marketing.read',
    'analytics.sales.read',
    'analytics.agents.read',
    'analytics.ai.read',
    'analytics.cost.read',
    'billing.read',
    'billing.manage',
  ],
  marketing_manager: [
    'campaigns.manage',
    'sources.manage',
    'forms.manage',
    'attribution.read',
    'analytics.marketing.read',
    'leads.create',
    'leads.read.team',
    'scoring.read',
    'scoring.edit',
    'automations.manage',
    'projects.read',
    'inventory.read',
    'knowledge.read',
    'ai.usage.read',
  ],
  sales_manager: [
    'team.performance.read',
    'agents.manage',
    'agents.availability.manage',
    'pipeline.configure',
    'pipeline.move',
    'assignment.configure',
    'leads.read.team',
    'leads.update',
    'leads.assign',
    'leads.reassign',
    'leads.classify.override',
    'conversations.read.private',
    'conversations.reply',
    'conversations.takeover',
    'conversations.transfer',
    'tasks.manage',
    'calls.manage',
    'sitevisits.read',
    'sitevisits.manage',
    'scoring.read',
    'scoring.edit',
    'scoring.approve',
    'scoring.publish',
    'projects.read',
    'inventory.read',
    'analytics.sales.read',
    'analytics.agents.read',
    'knowledge.read',
    'ai.settings.read',
    'ai.runs.read',
    'ai.test_lab.use',
    'ai.copilot.use',
    'ai.feedback.create',
    'ai.usage.read',
  ],
  sales_agent: [
    'leads.read.assigned',
    'leads.update',
    'conversations.read.assigned',
    'conversations.reply',
    'conversations.takeover',
    'pipeline.move',
    'tasks.manage',
    'calls.manage',
    'sitevisits.read',
    'sitevisits.manage',
    'projects.read',
    'inventory.read',
    'scoring.read',
    'knowledge.read',
    'ai.copilot.use',
    'ai.feedback.create',
  ],
  project_maintenance: [
    'projects.read',
    'projects.manage',
    'inventory.read',
    'inventory.manage',
    'inventory.import',
    'knowledge.manage',
    'knowledge.approve',
    'knowledge.read',
    'knowledge.create',
    'knowledge.edit',
    'knowledge.review',
    'knowledge.archive',
    'knowledge.conflicts.resolve',
    'staledata.resolve',
    // NOTE: intentionally NO conversations.read.private and NO ai.runs.read
    // (no private lead conversations, no AI runs with lead content) — §3.1.
  ],
  viewer: [
    'projects.read',
    'inventory.read',
    'leads.read.team',
    'sitevisits.read',
    'analytics.sales.read',
    'analytics.marketing.read',
    'analytics.agents.read',
    'attribution.read',
    'billing.read',
    'scoring.read',
    'knowledge.read',
  ],
};
